"""empty message

Revision ID: 16cf613d5aad
Revises: ed73c4cc5a38
Create Date: 2017-05-31 20:08:59.716972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '16cf613d5aad'
down_revision = 'ed73c4cc5a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sysdiagrams')
    op.drop_table('picture')
    op.create_foreign_key(None, '_picture_for_phrase', 'questionnaire', ['questionnaire_id'], ['id'])
    op.create_foreign_key(None, '_picture_for_phrase', 'phrase', ['phrase_id'], ['id'])
    op.create_foreign_key(None, '_possible_response', 'phrase', ['phrase1_id'], ['id'])
    op.create_foreign_key(None, '_possible_response', 'phrase', ['phrase2_id'], ['id'])
    op.create_foreign_key(None, '_possible_response', 'questionnaire', ['questionnaire_id'], ['id'])
    op.drop_constraint('FK__phrase__picture___34C8D9D1', 'phrase', type_='foreignkey')
    op.drop_column('phrase', 'picture_id')
    op.add_column('questionnaire', sa.Column('picture', sa.VARBINARY(), nullable=True))
    op.drop_column('questionnaire', 'picuture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire', sa.Column('picuture', mssql.VARBINARY(), autoincrement=False, nullable=True))
    op.drop_column('questionnaire', 'picture')
    op.add_column('phrase', sa.Column('picture_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('FK__phrase__picture___34C8D9D1', 'phrase', 'picture', ['picture_id'], ['id'])
    op.drop_constraint(None, '_possible_response', type_='foreignkey')
    op.drop_constraint(None, '_possible_response', type_='foreignkey')
    op.drop_constraint(None, '_possible_response', type_='foreignkey')
    op.drop_constraint(None, '_picture_for_phrase', type_='foreignkey')
    op.drop_constraint(None, '_picture_for_phrase', type_='foreignkey')
    op.create_table('picture',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.NVARCHAR(length=200), autoincrement=False, nullable=True),
                    sa.Column('filePath', sa.NVARCHAR(length=500), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='PK__picture__3213E83F314585B7')
    )
    op.create_table('sysdiagrams',
                    sa.Column('name', sa.NVARCHAR(length=128), autoincrement=False, nullable=False),
                    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
                    sa.Column('diagram_id', sa.INTEGER(), nullable=False),
                    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('diagram_id', name='PK__sysdiagr__C2B05B611B5FE055')
    )
    # ### end Alembic commands ###
